name: Remote Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Disable strict host key checking
        run: |
           echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
           
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Run update script on server
        run: ssh root@64.23.185.50 './update.sh'
